import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import { FavoritesProvider } from '@/shared/components/favorite-provider';
import { Toaster } from '@/shared/components/ui/sonner';
import { cn } from '@/shared/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <FavoritesProvider>
        <body
          className={cn(
            'grid min-h-[100dvh] grid-rows-1 bg-background font-sans antialiased',
            inter.variable
          )}
        >
          <main className="container my-6">{children}</main>
          <Toaster position="top-center" />
        </body>
      </FavoritesProvider>
    </html>
  );
}
